title = "SAFE Workshop"
baseURL = "https://safeworkshop.github.io"
languageCode = "en-us"
theme = ["ananke"]
# resourceDir = "./resources"

DefaultContentLanguage = "en"
SectionPagesMenu = "main"
Paginate = 3
googleAnalytics = ""
enableRobotsTXT = true

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[params]
  text_color = ""
  author = ""
  favicon = ""
  site_logo = ""
  description = "Workshop on Explainable and Safety Bounded, Fidelitous, Machine Learning for Networking @CoNEXT 2023"
  # choose a background color from any on this page: https://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-black"
  recent_posts_number = 1
  read_more_copy = "Click here to see more"
